### ISSUE TITLE
Devam Eden Animelerde Bölüm Ekleme Sorunu

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end-admin#1]
MAL (MyAnimeList) burada bitmedi gözüken animeleri eklerken bölümleri aç dersek mal da bitmediği için bölümleri açmıyor. Normalde çıktığı bölüme kadar açması lazım. Sanırsam bir bug.

**Comment by Hime-Dev** [comment]
Aklıma geldikçe yazıyorum bu da yine bir ilerde olabilecek güzel şeylerden biri kendi düşüncem.

Animelere link ekleme kısmı 1 kutucuk normalde bu kutucuğu çoğaltıp 4-5 eklemek güzel fakat onun yerine bir not defteri importer koyulup yanına not defteri içi:
1. Bölüm
-link
-link
2. Bölüm
-link
şeklinde olup tek seferde birden çok link ekleme özelliği güzel olabilir.

**Comment by ayberktandogan** [comment]
1. `if (req.body.getEpisodes && req.body.episode_count !== 0)` MyAnimeList devam eden bazı animelerde bölüm sayısı bilgisi vermiyor. Bu yüzden bölümler açılmamıştır.

2. #2
