### ISSUE TITLE
Download Link Ekleyememe

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end-admin#3]
16.02.2020 günü dahil hiçbir sorun yoktu 1 hafta boyunca sadece yeni gelen güncellemeleri yaptım ekstra bir şey eklemedim. Bugün baktığımda hiçbir indirme linkini ekleyemiyordum log dosyası nereye gidiyor bilmiyorum fakat console.log err de bir hata düşüyor link eklendiğinde. oda bu (_`-`_)

![fsff](https://user-images.githubusercontent.com/57987392/75092320-69ab4780-5587-11ea-8f05-b529542c4305.JPG)

**Comment by Hime-Dev** [comment]
dip not eski episode.js i attım denemek için sorun güncellemede sanırsam.

**Comment by ayberktandogan** [comment]
Sorun güncellemede değil. Bölüm kısmında bu şekilde hata verdirtecek herhangi bir düzenleme yapılmadı.

Daha fazla detay olmadığı için kapatıyorum.

**Comment by Hime-Dev** [comment]
Anlıyorum. Sorunu çözdüm şimdi fakat js vb çok fazla kod bilgim olmadığı için deneme yanılmayla eski episode.js ile yenisinde bulduğum tek fark 256-258 kod satırı

router.post('/indirme-linki-ekle', (req, res) => {
    is_perm(req.headers.authorization, "add-download-link").then(async ({ is_perm, username, user_id }) => {
        if (is_perm) {
            const extract = await downloadLinkExtract(req.body.link)

yenisinde async ve await yoktu bunları ekleyince sorun çözüldü tabi dediğim gibi çok fazla kod bilgim yok o yüzden emin değilim sorunun bununla olup olmadığı konusunda 

https://github.com/ForFansubs/node-server/blob/master/routes/api/episode.js

**Comment by ayberktandogan** [comment]
Sorunun ya episode.js ya da config/link-extraction-download.js dosyasında olması gerekiyor ki, ikisinde de sorun yok. Callback fonksiyonunu async olarak tanımlamaya da gerek yok, çünkü config/link-extraction-download.js dosyasında async bir şey yapılmıyor.

Herhangi bir dosyayı kendiniz düzenlediyseniz ona herhangi bir şekilde yardımcı olamam. Hatayı tekrarlayamıyorum çünkü.
