### ISSUE TITLE
[İSTEK] Sitenin PNG, JPG, GIF, APNG ve Genel Optimizasyonu

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/front-end-admin#8]
# Özellik isteği
Sitenin PNG, JPG, GIF, APNG ve Genel Optimizasyonu
## Özellik ayrıntıları
Sitenin %70 lik bir kısmı header cover, anime coverları vb resimlerden oluşuyor. Ve sitenin hızını büyük bir ölçüde etkiliyor pagespeed veya gtmetrix sonuçlarına sitede ki en büyük yavaşlatan öğlerden biri resimlerin optimizasyonu, ikincisi ise cache süreleri zaten diğer javascript benzeri kod durumundan yavaşlık söz konusu bile değil. (Siteye yavaş demiyorum kendim özelleştirip eklediğim sayfaların siteyi yavaşlatacağını biliyorum ama bu yukarıda dediğim iki şeyden birincisi genel olarak yapılması gereken bir optimizasyon özelliğidir.)
## Aşağıdakileri doğruluyorum:
- [x] Sistemde böyle bir özelliğin olup olmadığını buraya yazmadan önce araştırdım.

**Comment by ayberktandogan** [comment]
/ForFansubs/node-server#16
